name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls -l
    - name: ls2
      run: ls -l /
    - name: trypython
      run: which python
    - name: trygcc
      run: which gcc
    - name: trygcc2
      run: gcc main.cpp -lm
    - name: tryrun
      run: ./a.out
    - name: archiveartifacts
    - uses: actions/upload-artifact@v2
      with:
        name: "kickartifacts"
        path: kick.dat
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
